import pandas as pd 
import matplotlib.pyplot as plt 
while True: 
 print("*"*60) 
 print("\t\t\tBAKERY STORE") 
 print("*"*60) 
 print("1. Products ") 
 print("2. Sales ") 
 print("3. Customer Information") 
 print("4. Exit") 
 print("*"*60) 
 opt=int(input("Enter your choice ")) 
 if opt==1: 
       while True: 
             DF=pd.read_csv("projectcsv.csv", index_col='S.NO.') 
 print() 
 print("Products") 
 print()  
 print("1. Display all Products ")
 print("2. Add a new Product")
 print("3. Remove a Product ") 
 print("4. Modify product details ") 
 print("5. Search a Product") 
 print("6. Sort the Products ") 
 print("7. Display the Products with max. Stock") 
 print("8. Display Products which are out of Stock") 
 print("9. Bar Graph - Comparison of Prices") 
 print("10. Line Graph- Stock of Products") 
 print("11. Exit") 
 ch=int(input("Enter your choice ")) 
 if ch==1: 
            print("-"*60) 
            print(DF) 
            print("-"*60) 
            print() 
 elif ch==2: 
            p = DF.index.max()+1 
            n = input("Enter product name ") 
            cp = int(input("Enter the Cost Price ")) 
            sp = int(input("Enter the Selling Price ")) 
            s = int(input("Enter the Stock ")) 
            DF.loc[p] =[n,cp,sp,s] 
            DF.to_csv("projectcsv.csv")
            print("-"*60)
            print(DF) 
            print("-"*60) 
            print() 
            print("Record Saved") 
 elif ch==3: 
            p = int(input("Enter the S.No. to be removed ")) 
            print("-"*60) 
            print(DF.loc[p]) 
            print("-"*60) 
            print() 
            a = input("Are you sure to delete this product Y/N ") 
            if a=='Y' or a=='y': 
                  DF.drop(p, inplace=True) 
                  DF.to_csv("projectcsv.csv") 
                  print("-"*60) 
                  print(DF) 
                  print("-"*60) 
                  print() 
                  print("Record Deleted") 
            elif ch==4: 
                  p= int(input("Enter the S.NO. to be modified ")) 
                  print("-"*60) 
                  print(DF.loc[p])
                  print("-"*60)
                  print() 
                  a = input("Are you sure to modify this product Y/N ") 
                  if a=='Y' or a=='y': 
                        n = input("Enter product name ") 
                        cp = int(input("Enter the Cost Price ")) 
                        sp = int(input("Enter the Selling Price ")) 
                        s = int(input("Enter the Stock ")) 
                        DF.loc[p] =[n,cp,sp,s] 
                        DF.to_csv("projectcsv.csv") 
                        print("-"*60) 
                        print(DF) 
                        print("-"*60) 
                        print() 
                        print("Record Modified") 
                  elif ch==5: 
                        p = int(input("Enter the S.NO. to be searched ")) 
                        print("-"*60) 
                        print(DF.loc[p]) 
                        print("-"*60) 
                  elif ch==6: 
                        c = input("Enter the name of the column by which you want to sort the values ") 
                        print("-"*60)
                        print(DF.sort_values(c))
                        print("-"*60) 
                  elif ch==7: 
                        print("-"*60) 
                        print(DF.sort_values('Stock', ascending=False).head(5)) 
                        print("-"*60) 
                  elif ch==8: 
                        print("-"*60) 
                        print("Products out of stock") 
                        print("-"*60) 
                        print(DF[DF['Stock']==0]) 
                        print("-"*60) 
                  elif ch==9: 
                              DF[['CP','SP']].plot(kind='bar') 
                              plt.xticks(DF.index-1,DF['Name'], rotation=0) 
                              plt.xlabel('Product Name') 
                              plt.ylabel('Price') 
                              plt.title('Comparison of Prices') 
                              plt.show() 
                  elif ch==10: 
                              DF[['Name','Stock']].plot(kind='line') 
                              plt.xticks(DF.index,DF['Name']) 
                              plt.xlabel('Product Name') 
                              plt.ylabel('Stock')
                              plt.title('Stock Availability of Products')
                              plt.show() 
                  elif ch==11: 
                        break 
                  elif opt==2: 
                        DF=pd.read_csv("sales.csv", index_col='S.NO.') 
                        print("1. Display all Sales ") 
                        print("2. Add a new sale") 
                        print("3. Remove a sale ") 
                        print("4. Modify product sales ") 
                        print("5. Search a sale") 
                        print("6. Sort the sales ") 
                        print("7. Display the Products with max. Quantity") 
                        print("8. Bar Graph - Comparison of sales") 
                        print("9. Line Graph-Comparison of sales") 
                        print("10. Exit") 
                        ch=int(input("Enter your choice ")) 
                        if ch==1: 
                              print("-"*60) 
                              print(DF) 
                              print("-"*60) 
                              print() 
                        elif ch==2: 
                              a= DF.index.max()+1
                              b = input("Enter YEAR ")
                              c = int(input("Enter the Month ")) 
                              d = int(input("Enter the Customer ")) 
                              e = int(input("Enter the Quantity ")) 
                              f = int(input("Enter the Amount ")) 
                              DF.loc[p] =[a,b,c,d,e,f] 
                              DF.to_csv("sales.csv") 
                              print("-"*60) 
                              print(DF) 
                              print("-"*60) 
                              print() 
                              print("Record Saved") 
                        elif ch==3: 
                              p = int(input("Enter the S.No. to be removed ")) 
                              print("-"*60) 
                              print(DF.loc[p]) 
                              print("-"*60) 
                              print() 
                              a = input("Are you sure to delete this product Y/N ") 
                              if a=='Y' or a=='y': 
                                    DF.drop(p, inplace=True) 
                                    DF.to_csv("sales.csv") 
                                    print("-"*60) 
                                    print(DF)
                                    print("-"*60)
                                    print() 
                                    print("Record Deleted") 
                              elif ch==4: 
                                    p = int(input("Enter the S.NO. to be modified ")) 
                                    print("-"*60) 
                                    print(DF.loc[p]) 
                                    print("-"*60) 
                                    print() 
                                    a = input("Are you sure to modify this product Y/N ") 
                                    if a=='Y' or a=='y': 
                                          b = input("Enter YEAR ") 
                                          c = int(input("Enter the Month ")) 
                                          d = int(input("Enter the Customer ")) 
                                          e = int(input("Enter the Quantity ")) 
                                          f = int(input("Enter the Amount ")) 
                                          DF.loc[p] =[a,b,c,d,e,f] 
                                          DF.to_csv("sales.csv") 
                                          print("-"*60) 
                                          print(DF) 
                                          print("-"*60) 
                                          print() 
                                          print("Record Modified") 
                                    elif ch==5:
                                          p = int(input("Enter the S.NO. to be searched "))
                                          print("-"*60) 
                                          print(DF.loc[p]) 
                                          print("-"*60) 
                                    elif ch==6: 
                                          c = input("Enter the name of the column by which you want to sort the values ") 
                                          print("-"*60) 
                                          print(DF.sort_values(c)) 
                                          print("-"*60) 
                                    elif ch==7: 
                                                print("-"*60) 
                                                print(DF.sort_values('Amount', ascending=False).head(5)) 
                                                print("-"*60) 
                                    elif ch==8: 
                                                DF[['Month','Quantity']].plot(kind='bar') 
                                                plt.xticks(DF.index-1,DF['Month'], rotation=0) 
                                                plt.xlabel('Month') 
                                                plt.ylabel('Quantity') 
                                                plt.title('Comparison of Quantity by month') 
                                                plt.show() 
                                    elif ch==9: 
                                                DF[['Month','Amount']].plot(kind='line') 
                                                plt.xticks(DF.index,DF['Month'])
                                                plt.xlabel('Month')
                                                plt.ylabel('Amount') 
                                                plt.title('Comparison of Quantity by month') 
                                                plt.show() 
                                    elif ch==10: 
                                          break 
                                    elif opt==3: 
                                          DF=pd.read_csv("details.csv", index_col='S.NO.') 
                                          print("1. Display all details ") 
                                          print("2. Add a new detail") 
                                          print("3. Remove a detail ") 
                                          print("4. Modify product details ") 
                                          print("5. Search a detail") 
                                          print("6. Sort the details ") 
                                          print("7. Display the Products with max. Quantity") 
                                          print("8. Bar graph - Comparison of Quantity") 
                                          print("9. Line Graph- Quantity of Products") 
                                          print("10. Exit") 
                                          ch=int(input("Enter your choice ")) 
                                    if ch==1: 
                                                print("-"*60) 
                                                print(DF) 
                                                print("-"*60) 
                                                print()
                                    elif ch==2:
                                          p = DF.index.max()+1 
                                          n = input("Enter Customer name ") 
                                          c = int(input("Enter the PRODUCT ")) 
                                          q = int(input("Enter the Quantity ")) 
                                          s = int(input("Enter the Phone No. ")) 
                                          DF.loc[p] =[n,c,q,s] 
                                          DF.to_csv("details.csv") 
                                          print("-"*60) 
                                          print(DF) 
                                          print("-"*60) 
                                          print() 
                                          print("Record Saved") 
                                    elif ch==3: 
                                          p = int(input("Enter the S.No. to be removed ")) 
                                          print("-"*60) 
                                          print(DF.loc[p]) 
                                          print("-"*60) 
                                          print() 
                                          a = input("Are you sure to delete this product Y/N ") 
                                    if a=='Y' or a=='y': 
                                                DF.drop(p, inplace=True) 
                                                DF.to_csv("details.csv") 
                                                print("-"*60)
                                                print(DF)
                                                print("-"*60) 
                                                print() 
                                                print("Record Deleted") 
                                    elif ch==4: 
                                                p = int(input("Enter the S.NO. to be modified ")) 
                                                print("-"*60) 
                                                print(DF.loc[p]) 
                                                print("-"*60) 
                                                print() 
                                                a = input("Are you sure to modify this product Y/N ") 
                                    if a=='Y' or a=='y': 
                                          n = input("Enter customer name ") 
                                          c = int(input("Enter the PRODUCT ")) 
                                          q = int(input("Enter the Quantity ")) 
                                          s = int(input("Enter the Phone No. ")) 
                                          DF.loc[p] =[n,c,q,s] 
                                          DF.to_csv("projectcsv.csv") 
                                          print("-"*60) 
                                          print(DF) 
                                          print("-"*60) 
                                          print() 
                                          print("Record Modified") 
                                    elif ch==5:
                                          p = int(input("Enter the S.NO. to be searched "))
                                          print("-"*60) 
                                          print(DF.loc[p]) 
                                          print("-"*60) 
                                    elif ch==6: 
                                          c = input("Enter the name of the column by which you want to sort the values ") 
                                          print("-"*60) 
                                          print(DF.sort_values(c)) 
                                          print("-"*60) 
                                    elif ch==7: 
                                          print("-"*60) 
                                          print(DF.sort_values('Quantity', ascending=False).head(5)) 
                                          print("-"*60) 
                                    elif ch==8: 
                                          DF[['PRODUCT Purchased','Quantity']].plot(kind='bar') 
                                          plt.xticks(DF.index-1,DF['PRODUCT Purchased'], rotation=0) 
                                          plt.xlabel('Product') 
                                          plt.ylabel('Quantity') 
                                          plt.title('Comparison of Quantity purchased') 
                                          plt.show() 
                                    elif ch==9: 
                                          DF[['PRODUCT Purchased','Quantity']].plot(kind='line') 
                                          plt.xticks(DF.index,DF['PRODUCT Purchased'])
                                          plt.xlabel('PRODUCT Purchased')
                                          plt.ylabel('Quantity') 
                                          plt.title('Comparison of Quantity purchased') 
                                          plt.show() 
                                    elif ch==10: 
                                          break 
                                    elif opt==4: 
                                          break
